server:
  port: 9000
  servlet:
    context-path: /services
jdbc:
  driver:
    class:
      name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/school
  user: root
  password: Admin123
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school?verifyServerCertificate=false&useSSL=false&requireSSL=false
    data-username: root
    data-password: Admin123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect